name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: npm install
        run: npm install
        env:
          CI: true
      - name: npm test
        run: npm test
        env:
          CI: true
