name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
      - name: Install npm dependencies
        run: npm ci
      - name: Run tests
        run: npm test -- --ci
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5.5.1
