name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
      - name: Install npm dependencies
        run: npm ci
      - name: Run tests
        run: npm test -- --ci
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5.5.1
