name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install npm dependencies
        run: npm ci
      - name: Run tests
        run: npm test -- --ci
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.5.0
